source "https://rubygems.org"

gem 'no-style-please'
#gem "jekyll", "3.9"
gem "jekyll", "4.0"
gem "jekyll-feed"
gem "jekyll-remote-theme"
gem "jektex", "0.1.1"
gem "kramdown-parser-gfm"

#gem "github-pages", group: :jekyll_plugins
